#pragma once

typedef enum error_e
{
	SUCCESS,
	ERROR_INVALID_COMMAND_DATA,
	ERROR_INVALID_COMMAND_NAME,
	ERROR_OPEN_PROCESS_FAILURE,
	ERROR_MAX_BPS,
	ERROR_READ_WRITE_PROCESS,
	ERROR_NO_BP_AT_ADDRESS,
	ERROR_CONTEXT_FAILURE,
	ERROR_INVALID_DEBUG_EVENT,
	ERROR_INVALID_COMMAND_ARGUMENT,
	ERROR_HANDLE_COMMAND_FAILURE,
} error_t;
